"""
models/complaint_embedding.py — Sentence-BERT Embedding Store

Table: complaint_embeddings

Stores the dense vector embedding for each complaint, generated by
the all-MiniLM-L6-v2 SentenceTransformer model from:
    text = complaint.title + " " + complaint.description

Embeddings are serialised to JSON (float list) for portability across
MySQL versions that don't natively support vector types.

Schema notes:
  - One row per complaint (1:1 relationship).
  - embedding column: TEXT storing JSON array of 384 floats.
  - Deletion cascades with parent complaint.

Performance note:
  embedding is TEXT, not MEDIUMBLOB, so it works on all MySQL configs.
  For production scale (>100k complaints) consider pgvector or
  a dedicated vector store (Pinecone / Weaviate / Qdrant).
"""

import uuid
from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.base import Base


class ComplaintEmbedding(Base):
    __tablename__ = "complaint_embeddings"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )

    complaint_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("complaints.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,          # one embedding per complaint
        index=True,
    )

    # JSON-serialised float list: "[0.123, -0.456, ...]"  (384 dims for MiniLM)
    embedding: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="JSON-serialised float list — 384 dims for all-MiniLM-L6-v2",
    )

    created_at: Mapped[DateTime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Relationship ─────────────────────────────────────────────────────────
    complaint = relationship(
        "Complaint",
        back_populates="embedding_record",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return f"<ComplaintEmbedding id={self.id!r} complaint={self.complaint_id!r}>"
