"""
Chennai Corporation (GCC) — All 15 Zones + 201 Wards
=====================================================

Source: Greater Chennai Corporation official ward list
Format: zone_id / zone_number / zone_name → wards with ward_number and locality name

This file is the reference for creating Zonal Officers and Ward Officers
via the Admin panel. Use zone_id (DB primary key) when creating officers.

DB zone_id = zone_number (1 to 15) — they match exactly.

Each ward entry shows:
  - ward_number : official GCC ward number (1-200)
  - ward_name   : locality / area name
"""

CHENNAI_ZONES_AND_WARDS = [
    {
        "zone_id": 1,
        "zone_number": 1,
        "zone_name": "Thiruvottiyur",
        "wards": [
            {"ward_number": "1",  "ward_name": "Kathivakkam"},
            {"ward_number": "2",  "ward_name": "Moolakothalam"},
            {"ward_number": "3",  "ward_name": "Thiruvottiyur"},
            {"ward_number": "4",  "ward_name": "Theradi"},
            {"ward_number": "5",  "ward_name": "Kaladipet"},
            {"ward_number": "6",  "ward_name": "Vallur"},
            {"ward_number": "7",  "ward_name": "Ponneri High Road"},
            {"ward_number": "8",  "ward_name": "Vichoor"},
            {"ward_number": "9",  "ward_name": "Ennore"},
            {"ward_number": "10", "ward_name": "Kattukuppam"},
            {"ward_number": "11", "ward_name": "Pattalam"},
            {"ward_number": "12", "ward_name": "New Washermenpet"},
            {"ward_number": "13", "ward_name": "Mathur"},
            {"ward_number": "14", "ward_name": "Kodungaiyur"},
        ],
    },
    {
        "zone_id": 2,
        "zone_number": 2,
        "zone_name": "Manali",
        "wards": [
            {"ward_number": "15", "ward_name": "Manali New Town"},
            {"ward_number": "16", "ward_name": "Manali"},
            {"ward_number": "17", "ward_name": "Thiruninravur"},
            {"ward_number": "18", "ward_name": "Minjur"},
            {"ward_number": "19", "ward_name": "Madhurai Veeran Koil"},
            {"ward_number": "20", "ward_name": "Senneerkuppam"},
            {"ward_number": "21", "ward_name": "Surapet"},
        ],
    },
    {
        "zone_id": 3,
        "zone_number": 3,
        "zone_name": "Madhavaram",
        "wards": [
            {"ward_number": "22", "ward_name": "Madhavaram"},
            {"ward_number": "23", "ward_name": "Periyar Nagar"},
            {"ward_number": "24", "ward_name": "Kolathur"},
            {"ward_number": "25", "ward_name": "Villivakkam"},
            {"ward_number": "26", "ward_name": "Ambattur"},
            {"ward_number": "27", "ward_name": "Puzhal"},
            {"ward_number": "28", "ward_name": "Madhavaram Milk Colony"},
            {"ward_number": "29", "ward_name": "Redhills"},
            {"ward_number": "30", "ward_name": "Kathirvedu"},
            {"ward_number": "31", "ward_name": "Erukkanchery"},
            {"ward_number": "32", "ward_name": "Perambur Barracks"},
            {"ward_number": "33", "ward_name": "Kolathur (South)"},
            {"ward_number": "34", "ward_name": "Peravallur"},
        ],
    },
    {
        "zone_id": 4,
        "zone_number": 4,
        "zone_name": "Tondiarpet",
        "wards": [
            {"ward_number": "35", "ward_name": "Tondiarpet"},
            {"ward_number": "36", "ward_name": "Sembiyam"},
            {"ward_number": "37", "ward_name": "Perambur"},
            {"ward_number": "38", "ward_name": "Vyasarpadi"},
            {"ward_number": "39", "ward_name": "Washermanpet"},
            {"ward_number": "40", "ward_name": "Manali Old Town"},
            {"ward_number": "41", "ward_name": "Tiruvottiyur (South)"},
            {"ward_number": "42", "ward_name": "Thiru-Vi-Ka Nagar"},
            {"ward_number": "43", "ward_name": "Ayanavaram"},
            {"ward_number": "44", "ward_name": "Otteri"},
            {"ward_number": "45", "ward_name": "New Washermenpet (North)"},
            {"ward_number": "46", "ward_name": "Perambur (East)"},
            {"ward_number": "47", "ward_name": "Perambur (West)"},
        ],
    },
    {
        "zone_id": 5,
        "zone_number": 5,
        "zone_name": "Royapuram",
        "wards": [
            {"ward_number": "48", "ward_name": "Royapuram"},
            {"ward_number": "49", "ward_name": "Kasimedu"},
            {"ward_number": "50", "ward_name": "Tiruvottiyur Harbour"},
            {"ward_number": "51", "ward_name": "Pulianthope"},
            {"ward_number": "52", "ward_name": "Harbour (South)"},
            {"ward_number": "53", "ward_name": "Broadway"},
            {"ward_number": "54", "ward_name": "Park Town"},
            {"ward_number": "55", "ward_name": "Chintadripet"},
            {"ward_number": "56", "ward_name": "Mannadi"},
            {"ward_number": "57", "ward_name": "Flower Bazaar"},
            {"ward_number": "58", "ward_name": "Sowcarpet"},
        ],
    },
    {
        "zone_id": 6,
        "zone_number": 6,
        "zone_name": "Thiru-Vi-Ka Nagar",
        "wards": [
            {"ward_number": "59", "ward_name": "Purasaiwakkam"},
            {"ward_number": "60", "ward_name": "Egmore"},
            {"ward_number": "61", "ward_name": "Pudupet"},
            {"ward_number": "62", "ward_name": "Kilpauk"},
            {"ward_number": "63", "ward_name": "Chetpet"},
            {"ward_number": "64", "ward_name": "Aminjikarai"},
            {"ward_number": "65", "ward_name": "Nerkundram"},
            {"ward_number": "66", "ward_name": "Amjikarai (West)"},
            {"ward_number": "67", "ward_name": "Gopalapuram"},
            {"ward_number": "68", "ward_name": "Pattalam (South)"},
            {"ward_number": "69", "ward_name": "Vepery"},
            {"ward_number": "70", "ward_name": "Ayanavaram (South)"},
            {"ward_number": "71", "ward_name": "Kodungaiyur (South)"},
            {"ward_number": "72", "ward_name": "Kolathur (East)"},
        ],
    },
    {
        "zone_id": 7,
        "zone_number": 7,
        "zone_name": "Ambattur",
        "wards": [
            {"ward_number": "73", "ward_name": "Ambattur (North)"},
            {"ward_number": "74", "ward_name": "Ambattur Industrial Estate"},
            {"ward_number": "75", "ward_name": "Ambattur (South)"},
            {"ward_number": "76", "ward_name": "Padi"},
            {"ward_number": "77", "ward_name": "Annanur"},
            {"ward_number": "78", "ward_name": "Villivakkam (North)"},
            {"ward_number": "79", "ward_name": "Arumbakkam"},
            {"ward_number": "80", "ward_name": "Koyambedu"},
            {"ward_number": "81", "ward_name": "Mogappair (West)"},
            {"ward_number": "82", "ward_name": "Mogappair (East)"},
            {"ward_number": "83", "ward_name": "Anna Nagar West Extension"},
            {"ward_number": "84", "ward_name": "Nolambur"},
            {"ward_number": "85", "ward_name": "Thirumangalam"},
            {"ward_number": "86", "ward_name": "Madhuravoyal"},
        ],
    },
    {
        "zone_id": 8,
        "zone_number": 8,
        "zone_name": "Anna Nagar",
        "wards": [
            {"ward_number": "87",  "ward_name": "Anna Nagar (East)"},
            {"ward_number": "88",  "ward_name": "Anna Nagar (West)"},
            {"ward_number": "89",  "ward_name": "Shenoy Nagar"},
            {"ward_number": "90",  "ward_name": "Periyamet"},
            {"ward_number": "91",  "ward_name": "Pursaiwakkam (South)"},
            {"ward_number": "92",  "ward_name": "Ayanavaram (North)"},
            {"ward_number": "93",  "ward_name": "Kolathur (North)"},
            {"ward_number": "94",  "ward_name": "Virugambakkam"},
            {"ward_number": "95",  "ward_name": "Alapakkam"},
            {"ward_number": "96",  "ward_name": "Ramapuram"},
            {"ward_number": "97",  "ward_name": "Valasaravakkam"},
            {"ward_number": "98",  "ward_name": "Mugalivakkam"},
            {"ward_number": "99",  "ward_name": "Porur"},
        ],
    },
    {
        "zone_id": 9,
        "zone_number": 9,
        "zone_name": "Teynampet",
        "wards": [
            {"ward_number": "100", "ward_name": "Teynampet"},
            {"ward_number": "101", "ward_name": "Nungambakkam"},
            {"ward_number": "102", "ward_name": "Alwarpet"},
            {"ward_number": "103", "ward_name": "Thyagaraya Nagar"},
            {"ward_number": "104", "ward_name": "Mandaveli"},
            {"ward_number": "105", "ward_name": "Mylapore"},
            {"ward_number": "106", "ward_name": "Royapettah"},
            {"ward_number": "107", "ward_name": "Triplicane"},
            {"ward_number": "108", "ward_name": "Fort St. George"},
            {"ward_number": "109", "ward_name": "Harbour (North)"},
            {"ward_number": "110", "ward_name": "George Town"},
            {"ward_number": "111", "ward_name": "Thousand Lights"},
            {"ward_number": "112", "ward_name": "Shastri Nagar"},
        ],
    },
    {
        "zone_id": 10,
        "zone_number": 10,
        "zone_name": "Kodambakkam",
        "wards": [
            {"ward_number": "113", "ward_name": "Kodambakkam"},
            {"ward_number": "114", "ward_name": "Ashok Nagar"},
            {"ward_number": "115", "ward_name": "Vadapalani"},
            {"ward_number": "116", "ward_name": "Abirampuram"},
            {"ward_number": "117", "ward_name": "K.K. Nagar"},
            {"ward_number": "118", "ward_name": "Ekkatuthangal"},
            {"ward_number": "119", "ward_name": "Guindy"},
            {"ward_number": "120", "ward_name": "Ekkatuthangal (South)"},
            {"ward_number": "121", "ward_name": "St. Thomas Mount"},
            {"ward_number": "122", "ward_name": "Pallavaram"},
            {"ward_number": "123", "ward_name": "Pammal"},
            {"ward_number": "124", "ward_name": "Cowl Bazaar"},
            {"ward_number": "125", "ward_name": "Kotturpuram"},
            {"ward_number": "126", "ward_name": "Adambakkam"},
        ],
    },
    {
        "zone_id": 11,
        "zone_number": 11,
        "zone_name": "Valasaravakkam",
        "wards": [
            {"ward_number": "127", "ward_name": "Valasaravakkam (North)"},
            {"ward_number": "128", "ward_name": "Virugambakkam (West)"},
            {"ward_number": "129", "ward_name": "Saligramam"},
            {"ward_number": "130", "ward_name": "Arcot Road"},
            {"ward_number": "131", "ward_name": "Vadapalani (West)"},
            {"ward_number": "132", "ward_name": "Nesapakkam"},
            {"ward_number": "133", "ward_name": "Alwarthirunagar"},
            {"ward_number": "134", "ward_name": "Kattupakkam"},
            {"ward_number": "135", "ward_name": "Kundrathur"},
            {"ward_number": "136", "ward_name": "Gerugambakkam"},
            {"ward_number": "137", "ward_name": "Pozhichalur"},
            {"ward_number": "138", "ward_name": "Kovilambakkam"},
            {"ward_number": "139", "ward_name": "Sembakkam"},
            {"ward_number": "140", "ward_name": "Pallikaranai (North)"},
            {"ward_number": "141", "ward_name": "Nanmangalam"},
            {"ward_number": "142", "ward_name": "Chitlapakkam"},
        ],
    },
    {
        "zone_id": 12,
        "zone_number": 12,
        "zone_name": "Alandur",
        "wards": [
            {"ward_number": "143", "ward_name": "Alandur"},
            {"ward_number": "144", "ward_name": "St. Thomas Mount (South)"},
            {"ward_number": "145", "ward_name": "Meenambakkam"},
            {"ward_number": "146", "ward_name": "Tirusulam"},
            {"ward_number": "147", "ward_name": "Chromepet"},
            {"ward_number": "148", "ward_name": "Anakaputhur"},
            {"ward_number": "149", "ward_name": "Peerkankaranai"},
            {"ward_number": "150", "ward_name": "Vengaivasal"},
            {"ward_number": "151", "ward_name": "Velachery"},
            {"ward_number": "152", "ward_name": "Madipakkam"},
            {"ward_number": "153", "ward_name": "Ullagaram"},
            {"ward_number": "154", "ward_name": "Puzhuthivakkam"},
            {"ward_number": "155", "ward_name": "Neelankarai"},
        ],
    },
    {
        "zone_id": 13,
        "zone_number": 13,
        "zone_name": "Adyar",
        "wards": [
            {"ward_number": "156", "ward_name": "Adyar"},
            {"ward_number": "157", "ward_name": "Besant Nagar"},
            {"ward_number": "158", "ward_name": "Saidapet"},
            {"ward_number": "159", "ward_name": "Kotturpuram (West)"},
            {"ward_number": "160", "ward_name": "Nandanam"},
            {"ward_number": "161", "ward_name": "Indira Nagar"},
            {"ward_number": "162", "ward_name": "Thiruvanmiyur"},
            {"ward_number": "163", "ward_name": "Palavakkam"},
            {"ward_number": "164", "ward_name": "Injambakkam"},
            {"ward_number": "165", "ward_name": "Kottivakkam"},
            {"ward_number": "166", "ward_name": "Semmenchery"},
            {"ward_number": "167", "ward_name": "Sholinganallur (North)"},
        ],
    },
    {
        "zone_id": 14,
        "zone_number": 14,
        "zone_name": "Perungudi",
        "wards": [
            {"ward_number": "168", "ward_name": "Perungudi"},
            {"ward_number": "169", "ward_name": "Okkiyam Thoraipakkam"},
            {"ward_number": "170", "ward_name": "Kandanchavadi"},
            {"ward_number": "171", "ward_name": "Karapakkam"},
            {"ward_number": "172", "ward_name": "Kelambakkam"},
            {"ward_number": "173", "ward_name": "Navalur"},
            {"ward_number": "174", "ward_name": "Semmancheri"},
            {"ward_number": "175", "ward_name": "Siruseri"},
            {"ward_number": "176", "ward_name": "Padur"},
            {"ward_number": "177", "ward_name": "Pozhichalur (South)"},
            {"ward_number": "178", "ward_name": "Manimangalam"},
        ],
    },
    {
        "zone_id": 15,
        "zone_number": 15,
        "zone_name": "Sholinganallur",
        "wards": [
            {"ward_number": "179", "ward_name": "Sholinganallur"},
            {"ward_number": "180", "ward_name": "Perumbakkam"},
            {"ward_number": "181", "ward_name": "Medavakkam"},
            {"ward_number": "182", "ward_name": "Madambakkam"},
            {"ward_number": "183", "ward_name": "Kovilambakkam (East)"},
            {"ward_number": "184", "ward_name": "Pallikaranai"},
            {"ward_number": "185", "ward_name": "Alandur (South)"},
            {"ward_number": "186", "ward_name": "Selaiyur"},
            {"ward_number": "187", "ward_name": "Sithalapakkam"},
            {"ward_number": "188", "ward_name": "Chitlapakkam (South)"},
            {"ward_number": "189", "ward_name": "Anakaputhur (East)"},
            {"ward_number": "190", "ward_name": "Ayanambakkam"},
            {"ward_number": "191", "ward_name": "Peerkankaranai (South)"},
            {"ward_number": "192", "ward_name": "Vandalur"},
            {"ward_number": "193", "ward_name": "Narayanapuram"},
            {"ward_number": "194", "ward_name": "Urapakkam"},
            {"ward_number": "195", "ward_name": "Guduvanchery"},
            {"ward_number": "196", "ward_name": "Singaperumal Koil"},
            {"ward_number": "197", "ward_name": "Madurantagam"},
            {"ward_number": "198", "ward_name": "Tambaram (East)"},
            {"ward_number": "199", "ward_name": "Tambaram (West)"},
            {"ward_number": "200", "ward_name": "Pallavaram (South)"},
        ],
    },
]

if __name__ == "__main__":
    total = sum(len(z["wards"]) for z in CHENNAI_ZONES_AND_WARDS)
    print(f"\n{'='*60}")
    print(f"  GCC — {len(CHENNAI_ZONES_AND_WARDS)} Zones, {total} Wards")
    print(f"{'='*60}")
    for zone in CHENNAI_ZONES_AND_WARDS:
        wc = len(zone["wards"])
        print(f"\n  Zone {zone['zone_number']:2d} (ID={zone['zone_id']:2d}): {zone['zone_name']}  [{wc} wards]")
        for w in zone["wards"]:
            print(f"    Ward {w['ward_number']:>3} — {w['ward_name']}")
    print(f"\n{'='*60}")
    print(f"  Total wards: {total}")
    print(f"{'='*60}\n")
